version: '3.3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app-1:
    image: myapp
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis
    depends_on:
      - redis

  app-2:
    image: myapp
    ports:
      - "8081:8080"
    environment:
      REDIS_URL: redis
    depends_on:
      - redis

  app-3:
    image: myapp
    ports:
      - "8082:8080"
    environment:
      REDIS_URL: redis
    depends_on:
      - redis